/**
* Turkson Cars Rental Database
* This describes the database of the cars rental application
*
* @author Joojo Quartey
* @author 10671406
* @version 1.0.0
* 
**/


DROP DATABASE IF EXISTS CarsRental

CREATE DATABASE CarsRental

USE CarsRental

CREATE TABLE tbl_customers (
	ID INT NOT NULL IDENTITY(1,1),
	FIRSTNAME VARCHAR(255) NOT NULL,
	LASTNAME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY(ID)
)

CREATE TABLE tbl_cars (
	ID INT NOT NULL IDENTITY(1,1),
	MAKE VARCHAR(255) NOT NULL,
	MODEL VARCHAR(255) NOT NULL,
	RENTED BIT NOT NULL,
	TRANSMISSION VARCHAR(255) NOT NULL,
	NUMBEROFDOORS VARCHAR(255) NOT NULL,
	BODYTYPE VARCHAR(255) NOT NULL,
	PLATE VARCHAR(255) NOT NULL,
	MODELYEAR VARCHAR(255) NOT NULL,
	CPD FLOAT NOT NULL,
	PRIMARY KEY(ID)
)


CREATE TABLE tbl_rentals (
	ID INT NOT NULL IDENTITY(1,1),
	ISSUEDATE DATE NOT NULL,
	RETURNSTATUS BIT NOT NULL,
	CUSTID INT NOT NULL,
	CARID INT NOT NULL,
	RETURNDATE DATE NOT NULL,
	DUEDATE DATE NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(CUSTID) REFERENCES tbl_customers(ID),
	FOREIGN KEY(CARID) REFERENCES tbl_cars(ID)
)